name: mongo-sharding

services:
  configSvr:
    container_name: configSvr
    image: mongo:latest
    restart: always
    ports:
      - "27019:27019"
    command:
      [
        "mongod",
        "--configsvr",
        "--replSet",
        "configSvr",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 20s
      timeout: 3s
      retries: 3  
    networks:
      - black_friday_network
    volumes:
      - configSvr-data:/data/db
  mongodb1: 
    container_name: mongodb1
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    command:
      [
        "mongos",
        "--configdb",
        "configSvr/configSvr:27019",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 20s
      timeout: 3s
      retries: 3
    depends_on:
      - configSvr
    networks:
      - black_friday_network
  shard1:
    container_name: shard1
    image: mongo:latest
    restart: always
    ports:
      - "27018:27018"
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 20s
      timeout: 3s
      retries: 3
    networks:
      - black_friday_network
    volumes:
      - shard1-data:/data/db
  shard2:
    container_name: shard2
    image: mongo:latest
    restart: always
    ports:
      - "27020:27020"
    command:
      [
        "mongod",
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27020", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 20s
      timeout: 3s
      retries: 3
    networks:
      - black_friday_network
    volumes:
      - shard2-data:/data/db
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongodb1
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongodb1:27017"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - black_friday_network

networks:
  black_friday_network:
    driver: bridge

volumes:
  configSvr-data:
  shard1-data:
  shard2-data: 
