name: mongo-sharding-repl-cache

services:
  configsvr:
    image: mongo:6
    container_name: configsvr
    command: ['mongod', '--configsvr', '--replSet', 'cfgRS', '--port', '27017']
    ports:
      - '27017:27017'
    volumes:
      - config_data:/data/db

  shard1-primary:
    image: mongo:6
    container_name: shard1-primary
    command: ['mongod', '--shardsvr', '--replSet', 'shard1RS', '--port', '27018']
    ports:
      - '27018:27018'
    volumes:
      - shard1_primary_data:/data/db

  shard1-secondary1:
    image: mongo:6
    container_name: shard1-secondary1
    command: ['mongod', '--shardsvr', '--replSet', 'shard1RS', '--port', '27018']
    volumes:
      - shard1_secondary1_data:/data/db

  shard1-secondary2:
    image: mongo:6
    container_name: shard1-secondary2
    command: ['mongod', '--shardsvr', '--replSet', 'shard1RS', '--port', '27018']
    volumes:
      - shard1_secondary2_data:/data/db

  shard2-primary:
    image: mongo:6
    container_name: shard2-primary
    command: ['mongod', '--shardsvr', '--replSet', 'shard2RS', '--port', '27019']
    ports:
      - '27019:27019'
    volumes:
      - shard2_primary_data:/data/db

  shard2-secondary1:
    image: mongo:6
    container_name: shard2-secondary1
    command: ['mongod', '--shardsvr', '--replSet', 'shard2RS', '--port', '27019']
    volumes:
      - shard2_secondary1_data:/data/db

  shard2-secondary2:
    image: mongo:6
    container_name: shard2-secondary2
    command: ['mongod', '--shardsvr', '--replSet', 'shard2RS', '--port', '27019']
    volumes:
      - shard2_secondary2_data:/data/db

  mongos:
    image: mongo:6
    container_name: mongos
    depends_on:
      - configsvr
    command: mongos --configdb cfgRS/configsvr:27017 --bind_ip_all
    ports:
      - '27020:27017'

  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6375:6379'

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
      - redis
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: 'mongodb://mongos:27017'
      MONGODB_DATABASE_NAME: 'somedb'
      REDIS_URL: 'redis://redis:6379'

volumes:
  config_data:
  shard1_primary_data:
  shard1_secondary1_data:
  shard1_secondary2_data:
  shard2_primary_data:
  shard2_secondary1_data:
  shard2_secondary2_data:
