version: '3'

services:
  config_service_1:
    image: mongo:latest
    container_name: config_service_1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data-1:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_repl",
        "--bind_ip_all",
        "--port", "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  config_service_2:
    image: mongo:latest
    container_name: config_service_2
    restart: always
    ports:
      - "27027:27017"
    volumes:
      - config-data-2:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_repl",
        "--bind_ip_all",
        "--port", "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  config_service_3:
    image: mongo:latest
    container_name: config_service_3
    restart: always
    ports:
      - "27037:27017"
    volumes:
      - config-data-3:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_repl",
        "--bind_ip_all",
        "--port", "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1_primary:
    image: mongo:latest
    container_name: shard1_primary
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard1-primary-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1_repl",
        "--bind_ip_all",
        "--port", "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1_secondary_1:
    image: mongo:latest
    container_name: shard1_secondary_1
    restart: always
    ports:
      - "27028:27018"
    volumes:
      - shard1-secondary1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1_repl",
        "--bind_ip_all",
        "--port", "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1_secondary_2:
    image: mongo:latest
    container_name: shard1_secondary_2
    restart: always
    ports:
      - "27038:27018"
    volumes:
      - shard1-secondary2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1_repl",
        "--bind_ip_all",
        "--port", "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2_primary:
    image: mongo:latest
    container_name: shard2_primary
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - shard2-primary-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2_repl",
        "--bind_ip_all",
        "--port", "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2_secondary_1:
    image: mongo:latest
    container_name: shard2_secondary_1
    restart: always
    ports:
      - "27029:27019"
    volumes:
      - shard2-secondary1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2_repl",
        "--bind_ip_all",
        "--port", "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2_secondary_2:
    image: mongo:latest
    container_name: shard2_secondary_2
    restart: always
    ports:
      - "27039:27019"
    volumes:
      - shard2-secondary2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2_repl",
        "--bind_ip_all",
        "--port", "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    depends_on:
      - config_service_1
      - config_service_2
      - config_service_3
    command:
      [
        "mongos",
        "--configdb",
        "config_repl/config_service_1:27017,config_service_2:27017,config_service_3:27017",
        "--bind_ip_all",
        "--port", "27020"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  mongo_sharding_repl:
    container_name: mongo_sharding_repl
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos_router
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020/?readPreference=secondaryPreferred"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  config-data-1:
  config-data-2:
  config-data-3:
  shard1-primary-data:
  shard1-secondary1-data:
  shard1-secondary2-data:
  shard2-primary-data:
  shard2-secondary1-data:
  shard2-secondary2-data:
